name: 'build-test'
on:
  push

jobs:
  build-and-liveness-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - uses: actions/checkout@v3
      - run: cd examples && ./docker-build.sh
      - run: cd examples && ARCH=$(arch) docker compose --verbose up --build --wait
